#encoding: utf-8
#author andy 2013-08-20

class ConstantValue

  PRODUCT_TYPE_ID           =   1

  CUSTOMER_TYPE_ID          =   3

  ENTITY_IS_ACTIVE          =   1

  ENTITY_IS_NOT_ACTIVE      =   0

  FLASHSALES_RULE_ID        =   1

  NORMAL_CUSTOMER_GROUD_ID  =   1

  COPPER_CUSTOMER_GROUD_ID  =   2

  SILVER_CUSTOMER_GROUD_ID  =   3

  GOLD_CUSTOMER_GROUD_ID    =   4

  DIAMOND_CUSTOMER_GROUD_ID =   5


#订单状态
  CANCELED_SALES_ORDER_STATUS = 1

  CLOSED_SALES_ORDER_STATUS   = 2

  COMPLETE_SALES_ORDER_STATUS = 3

  HOLDED_SALES_ORDER_STATUS = 4

  PENDING_SALES_ORDER_STATUS = 5

  PENDING_PAYMENT_SALES_ORDER_STATUS = 6

  PROCESSING_SALES_ORDER_STATUS = 7

  PENDING_DELIVERING_SALES_ORDER_STATUS = 8

  DELIVERING_SALES_ORDER_STATUS = 9

  REFUNDING_SALES_ORDER_STATUS = 10

 #商品类型
  PACKAGES_PRODUCT_TYPE_ID     = 1

  SERIES_PRODUCT_TYPE_ID       = 2

  SINGLE_PRODUCT_TYPE_ID       = 3

  VIRTUAL_PRODUCT_TYPE_ID      = 4

  BINGDING_PRODUCT_TYPE_ID     = 5
end